export declare const DEFAULT_PORT = 7777;
export declare const DISCOVERY_PORT = 7778;
export declare const WEBRTC_PORT = 7779;
export declare const SERVICE_NAME = "portal-fusion";
export declare const MDNS_SERVICE_TYPE = "_portal-fusion._tcp";
export declare const CONNECTION_TIMEOUT = 30000;
export declare const HEARTBEAT_INTERVAL = 5000;
export declare const RECONNECT_INTERVAL = 3000;
export declare const MAX_RECONNECT_ATTEMPTS = 10;
export declare const CHUNK_SIZE: number;
export declare const MAX_FILE_SIZE: number;
export declare const TRANSFER_TIMEOUT = 60000;
export declare const MAX_CONCURRENT_TRANSFERS = 5;
export declare const KEY_LENGTH = 256;
export declare const SALT_LENGTH = 32;
export declare const IV_LENGTH = 16;
export declare const TAG_LENGTH = 16;
export declare const PBKDF2_ITERATIONS = 100000;
export declare const SESSION_TIMEOUT: number;
export declare const PIN_LENGTH = 6;
export declare const QR_CODE_SIZE = 256;
export declare const DEFAULT_FRAME_RATE = 30;
export declare const MIN_FRAME_RATE = 5;
export declare const MAX_FRAME_RATE = 60;
export declare const QUALITY_PRESETS: {
    readonly low: {
        readonly width: 854;
        readonly height: 480;
        readonly bitrate: 500000;
        readonly frameRate: 15;
    };
    readonly medium: {
        readonly width: 1280;
        readonly height: 720;
        readonly bitrate: 1500000;
        readonly frameRate: 30;
    };
    readonly high: {
        readonly width: 1920;
        readonly height: 1080;
        readonly bitrate: 4000000;
        readonly frameRate: 30;
    };
    readonly lossless: {
        readonly width: -1;
        readonly height: -1;
        readonly bitrate: 10000000;
        readonly frameRate: 60;
    };
};
export declare const MAX_CLIPBOARD_TEXT_SIZE: number;
export declare const MAX_CLIPBOARD_IMAGE_SIZE: number;
export declare const CLIPBOARD_SYNC_DELAY = 500;
export declare const NOTIFICATION_TIMEOUT = 10000;
export declare const MAX_NOTIFICATION_ACTIONS = 3;
export declare const NOTIFICATION_ICON_SIZE = 256;
export declare const MOUSE_SMOOTHING = true;
export declare const KEYBOARD_REPEAT_DELAY = 500;
export declare const KEYBOARD_REPEAT_INTERVAL = 50;
export declare const TOUCH_HOLD_THRESHOLD = 500;
export declare const GESTURE_THRESHOLD = 50;
export declare const MAX_MESSAGE_QUEUE_SIZE = 1000;
export declare const MESSAGE_BATCH_SIZE = 10;
export declare const COMPRESSION_THRESHOLD = 1024;
export declare const CACHE_SIZE: number;
export declare const ANIMATION_DURATION = 200;
export declare const TOAST_DURATION = 3000;
export declare const THEME_STORAGE_KEY = "portal-fusion-theme";
export declare const SETTINGS_STORAGE_KEY = "portal-fusion-settings";
export declare const getPlatformPaths: () => {
    config: string;
    cache: string;
    logs: string;
    data: string;
};
export declare const ERROR_CODES: {
    readonly CONNECTION_FAILED: "E1000";
    readonly CONNECTION_TIMEOUT: "E1001";
    readonly CONNECTION_REFUSED: "E1002";
    readonly CONNECTION_LOST: "E1003";
    readonly AUTH_FAILED: "E2000";
    readonly AUTH_EXPIRED: "E2001";
    readonly AUTH_INVALID_TOKEN: "E2002";
    readonly AUTH_PERMISSION_DENIED: "E2003";
    readonly TRANSFER_FAILED: "E3000";
    readonly TRANSFER_CANCELLED: "E3001";
    readonly TRANSFER_CHECKSUM_MISMATCH: "E3002";
    readonly TRANSFER_SIZE_EXCEEDED: "E3003";
    readonly PROTOCOL_VERSION_MISMATCH: "E4000";
    readonly PROTOCOL_INVALID_MESSAGE: "E4001";
    readonly PROTOCOL_UNSUPPORTED_FEATURE: "E4002";
    readonly SYSTEM_PERMISSION_DENIED: "E5000";
    readonly SYSTEM_RESOURCE_UNAVAILABLE: "E5001";
    readonly SYSTEM_OPERATION_FAILED: "E5002";
    readonly UNKNOWN_ERROR: "E9999";
};
export declare const FEATURES: {
    readonly CLIPBOARD_SYNC: true;
    readonly FILE_TRANSFER: true;
    readonly SCREEN_SHARE: true;
    readonly REMOTE_CONTROL: true;
    readonly NOTIFICATIONS: true;
    readonly BROWSER_SYNC: true;
    readonly AUDIO_ROUTING: true;
    readonly CAMERA_SHARING: true;
    readonly TOUCH_INPUT: true;
    readonly STYLUS_INPUT: true;
    readonly BIOMETRIC_AUTH: false;
    readonly END_TO_END_ENCRYPTION: true;
    readonly COMPRESSION: true;
    readonly AUTO_DISCOVERY: true;
    readonly CLOUD_RELAY: false;
};
export declare const PATTERNS: {
    readonly IP_ADDRESS: RegExp;
    readonly MAC_ADDRESS: RegExp;
    readonly UUID: RegExp;
    readonly SEMVER: RegExp;
};
//# sourceMappingURL=constants.d.ts.map